Unbreak lower constraints
Before this lc job on stable/victoria fails with:

ERROR: Cannot install bandit<1.7.0 and >=1.6.0 because these package
versions have conflicting dependencies.

The conflict is caused by:
    The user requested bandit<1.7.0 and >=1.6.0
    The user requested (constraint) bandit==1.1.0

Change-Id: I2c434eb78b879f796cffb37c52e83e78ca775629