Fix signal handler for threading mode
Signal handler can only be set and executed in the main
thread of process. But in threading mode backend, they
are started on a new thread (in _handle_signal() method)
which does not work and raise error:

    ValueError: signal only works in main thread of the main interpreter

Threading backend's SignalHanlder class was added on the same line as
the eventlet backend's SignalHanlder[1]. In eventlet, it worked fine
for greenthread which run as part of OS main thread but in threading backend,
a new thread is separate from main thread so we need to make sure that
signal handler are set or called on the main thread itself.

[1] https://github.com/openstack/oslo.service/blob/9ca3b4a3e5c3d976ba57205791d250b1ca223ed6/oslo_service/backend/_eventlet/service.py#L60
Change-Id: I33ae7480d3bfe2100a4daf025556aec00c230191
Signed-off-by: Ghanshyam Maan <gmaan@ghanshyammann.com>